[[language]]
name = "typst"
language-servers = ["tinymist"]

[[grammar]]
name = "c3"
[grammar.source]
git = "https://github.com/c3lang/tree-sitter-c3.git"
rev = "main"

[[language]]
name = "c3"
scope = "source.c3"
file-types = ["c3", "c3i"]
roots = ["project.json"]
comment-token = "//"
language-servers = ["c3-lsp"] #if you want LSP support
[language.block-comment-tokens]
end = "*/"
start = "/*"

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true
# language-servers = ["emmet-ls"]

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true

#LSP support
[language-server.c3-lsp]
command = "c3lsp"

[language-server.tinymist]
command = "tinymist"
config = { preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"] }

# [language-server.emmet-ls]
# args = ["--stdio"]
# command = "emmet-ls"
